create table conversations (
  -- 각 대화방의 고유 ID (자동 증가)
  id bigint generated by default as identity primary key,
  -- 대화방 목록
  title text,
  -- 생성시간
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1. 각 대화메시지를 저장할 테이블 생성
CREATE TABLE messages (
  -- 각 메시지의 고유 ID
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- 어떤 대화방에 속하는지 (conversations 테이블 참조)
  conversation_id BIGINT REFERENCES conversations(id) NOT NULL,
  
  -- 메시지 역할(사용자, 어시스턴트, 시스템)
  role TEXT CHECK (role IN ('user', 'assistant', 'system')) NOT NULL,
  
  -- 메시지 내용
  content TEXT NOT NULL,
  
  -- 생성 시간 (괄호 위치와 NOT NULL 순서 수정)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 인덱스 생성 (테이블 생성 구문 밖에서 실행해야 합니다)
-- 오타 수정: conservation -> conversation / conversion -> conversation
CREATE INDEX messages_conversation_id_idx ON messages (conversation_id);